all:
    player:
        daily:
            easy:
                example_id:
                    name: example name
                    description: aboba
                    exp: 100
                    live_time: 3600
                    on_complete: # выполнится для всех исполнителей
                        - say {player} aboba
                    on_fail:
                        - say {player} ne aboba
                    on_complete_once:
                        - say {UUID} quest end aboba
                    on_fail_once:
                        - say {UUID} quest end ne aboba
                    conditions:
                        - walk:
                            # block: dirt
                            range: 
                                - 1
                                - 10
                        - jump:
                            # block: dirt 
                            range: 
                                - 10
                                - 100
                        - kill:
                            # entity: zombie
                            range: 
                                - 10
                                - 100
                        - block:
                            action: click # placement | destroy | l_click | r_click
                            # block: ice
                            range: 
                                - 10
                                - 100
                        - damage:
                            direction: e2p # p2e
                            # entity: FROG
                            range: 
                                - 10
                                - 100
                        - craft:
                          # item: bed
                            range: 
                                - 10
                                - 100
        weekly:
        monthly:
    clan:
        daily:
        weekly:
        monthly: